export enum OpCodes {
    AUTH = 0,
    HEARTBEAT = 1,
    HEARTBEAT_ACK = 2,
    VERIFIED_USER = 3,
    STAFF_CONNEXION_CREATED = 4,
    STAFF_CONNEXION_SUCCESS = 5,
    STAFF_CONNEXION_FAIL = 6,
    SANCTION_CREATED = 7,
}